server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/api/prom/push

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
      - localhost
    labels:
      job: prometheuslogs
      __path__: /root/log/prometheus.log
- job_name: node_exporter
  static_configs:
  - targets:
      - localhost
    labels:
      job: nodelogs
      __path__: /root/log/node_exporter.log
- job_name: loki
  static_configs:
  - targets:
      - localhost
    labels:
      job: lokilogs
      __path__: /root/log/loki.log
- job_name: supervisord
  static_configs:
  - targets:
      - localhost
    labels:
      job: superlogs
      __path__: /root/log/supervisord.log
