global:
  evaluation_interval: 15s
  scrape_timeout: 50s
  external_labels:
    monitor: QFlame
  scrape_interval: 1m
rule_files: [host.rule.yml]
# For example InfluxDB
#remote_write:
#  - url: "http://localhost:8086/api/v1/prom/write?db=prometheus"
#remote_read:
#  - url: "http://localhost:8086/api/v1/prom/read?db=prometheus"

scrape_configs:
- file_sd_configs:
  - files:
    - host.yaml
  job_name: 'node_exporter'
  metrics_path: /metrics

- job_name: 'prometheus'
  scrape_interval: 15s
  static_configs:
    - targets:
      - 'localhost:9090'

alerting:
  alert_relabel_configs:
    - source_labels: [product_type, ip]
      regex: (.*);(.*)
      target_label: routing_key
      replacement: ${1}__${2}
  alertmanagers:
    - static_configs:
      - targets:
        - 'localhost:9093'
