# # config file version
apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    basicAuth: 0
    isDefault: 1
    jsonData:
       httpMethod: "GET"
    editable: false
  - name: loki
    type: loki
    orgID: 2
    access: proxy
    url: http://localhost:3100
    basicAuth: 0
    isDefault: 0
    editable: false

